Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos est minus molestiae eveniet ab iusto, delectus beatae quisquam quidem, voluptates excepturi tempore repellat sint? Laborum vel qui illum, laudantium suscipit sed dolores necessitatibus perspiciatis cum tempora reprehenderit ullam ab aliquid quod fugit, temporibus incidunt eius aspernatur facilis ea quo odit eveniet! Facilis nihil saepe et voluptates! Consequuntur aliquid quia eum modi animi ipsum nostrum vel, accusantium cupiditate consectetur iusto dolore, facere, delectus vero iste necessitatibus quidem pariatur eligendi sequi itaque voluptates fuga. Illo vel laborum fugiat? Quae facere veritatis saepe voluptate vitae similique officia qui error, veniam pariatur neque soluta!


Post::create([
    'title' => 'Judul ke Empat',
    'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus eius voluptates id itaque laborum a accusamus, ea facere quam dignissimos fugiat totam, consectetur expedita magnam voluptatum ipsa laudantium architecto quos quibusdam harum sunt facilis.'
    'body' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus eius voluptates id itaque laborum a accusamus, ea facere quam dignissimos fugiat totam, consectetur expedita magnam voluptatum ipsa laudantium architecto quos quibusdam harum sunt facilis. Possimus est nobis accusantium exercitationem aperiam beatae, suscipit dicta ad accusamus eos pariatur dolorem distinctio illo sit velit aliquam earum assumenda ipsum natus vel, quisquam harum dignissimos libero? Assumenda perferendis fuga tempore, est omnis beatae ullam ab reiciendis id, fugiat repellat praesentium vitae suscipit iusto eum atque quibusdam voluptas repellendus doloribus at.</p><p> Deserunt neque blanditiis natus autem consequuntur esse vero, earum voluptas nisi temporibus hic praesentium vel, architecto, molestias iusto reprehenderit laborum consectetur. Numquam doloribus, excepturi labore atque voluptatem itaque quas quae sequi voluptates, molestiae corrupti minus asperiores maiores eum ea blanditiis, ipsa facere in vel veritatis ex. Quasi, dolore illum ut quisquam error aspernatur in nobis animi ab enim eius reiciendis minima pariatur ratione odio facilis nam. Saepe neque deserunt minus tenetur adipisci vitae rerum praesentium? Nam accusantium doloribus error blanditiis sapiente impedit sunt tempore officiis similique, debitis tempora unde, mollitia consequuntur repudiandae fugit incidunt eos consequatur totam, pariatur velit? Hic, qui quae ducimus sequi, nihil eveniet dignissimos, eligendi possimus accusamus ex molestiae dolorum ut?'</p>
    ])

Category::create([
    'name'=> 'Web Design',
    'slug'=> 'web-design'
    ])