<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus vitae perspiciatis repellendus alias at neque pariatur ipsum harum eum, nesciunt aspernatur assumenda beatae enim rem dolorum ipsam natus, exercitationem magnam asperiores? Quaerat beatae amet facilis dignissimos, odio provident aliquid fugiat, sequi maiores, ut enim quod fugit modi molestiae non nemo!</p><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae, labore deserunt ducimus quam dolores aut aspernatur, consequuntur nesciunt placeat animi enim iure error? Voluptatibus, magnam!</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem, doloremque nesciunt? Quis, sit voluptate suscipit incidunt exercitationem esse natus voluptatum distinctio quod iure adipisci nobis nihil voluptatibus inventore ab error eligendi labore atque repellendus vel.</p>

Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, veritatis natus eaque deserunt non quasi.

Post::create([
    'title' => 'Judul ke Empat',
    category_id = 1,
    slug
    'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus eius voluptates id itaque laborum a accusamus, ea facere quam dignissimos fugiat totam, consectetur expedita magnam voluptatum ipsa laudantium architecto quos quibusdam harum sunt facilis.'
    'body' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus eius voluptates id itaque laborum a accusamus, ea facere quam dignissimos fugiat totam, consectetur expedita magnam voluptatum ipsa laudantium architecto quos quibusdam harum sunt facilis. Possimus est nobis accusantium exercitationem aperiam beatae, suscipit dicta ad accusamus eos pariatur dolorem distinctio illo sit velit aliquam earum assumenda ipsum natus vel, quisquam harum dignissimos libero? Assumenda perferendis fuga tempore, est omnis beatae ullam ab reiciendis id, fugiat repellat praesentium vitae suscipit iusto eum atque quibusdam voluptas repellendus doloribus at.</p><p> Deserunt neque blanditiis natus autem consequuntur esse vero, earum voluptas nisi temporibus hic praesentium vel, architecto, molestias iusto reprehenderit laborum consectetur. Numquam doloribus, excepturi labore atque voluptatem itaque quas quae sequi voluptates, molestiae corrupti minus asperiores maiores eum ea blanditiis, ipsa facere in vel veritatis ex. Quasi, dolore illum ut quisquam error aspernatur in nobis animi ab enim eius reiciendis minima pariatur ratione odio facilis nam. Saepe neque deserunt minus tenetur adipisci vitae rerum praesentium? Nam accusantium doloribus error blanditiis sapiente impedit sunt tempore officiis similique, debitis tempora unde, mollitia consequuntur repudiandae fugit incidunt eos consequatur totam, pariatur velit? Hic, qui quae ducimus sequi, nihil eveniet dignissimos, eligendi possimus accusamus ex molestiae dolorum ut?'</p>
    ])

Category::create([
    'name'=> 'Web Design',
    'slug'=> 'web-design'
    ])

    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptate quisquam beatae dolorum ipsa veritatis, quae aspernatur assumenda ea, tempora reprehenderit placeat fugit et deleniti culpa. 
    
    Atque commodi expedita beatae, eos corrupti ut nesciunt architecto itaque soluta, magnam facilis? Saepe maxime quaerat, dolores incidunt doloribus placeat fugiat corrupti ratione adipisci hic officia voluptas similique eaque modi facere ducimus voluptatum ipsum exercitationem rem itaque, voluptate eos culpa voluptatibus? Fugiat deserunt nostrum magnam aspernatur explicabo, odio voluptatem. Quas iste commodi ab.


    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam eligendi ipsum dolor, sequi deleniti, dignissimos rem, iure soluta incidunt odio praesentium dolorum repellat odit molestias exercitationem dolorem vel saepe eveniet nulla animi facilis vero esse non? Accusamus magnam rem ipsam? Ab eos suscipit, beatae, natus aperiam laudantium veritatis atque mollitia deleniti tenetur enim nesciunt minus quasi accusantium qui accusamus perspiciatis. Placeat illo delectus omnis cupiditate.

    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta praesentium dignissimos quaerat accusantium, ipsa hic? Itaque similique possimus saepe enim praesentium quo dolores sapiente aliquam, fugiat at sed vero nesciunt, facere repudiandae architecto repellendus, officia nostrum eligendi ipsum est voluptate. Veritatis voluptas ad amet, temporibus provident ratione ipsam ipsa cumque libero. Possimus porro saepe vel nobis animi distinctio quia. Tempore, quae odio placeat dolorem nulla consequuntur facilis nobis nam incidunt praesentium, sit dignissimos explicabo! Sint possimus eum ea doloribus impedit repellat eveniet voluptatibus culpa molestias nisi architecto quaerat molestiae quas numquam modi ullam veniam reiciendis, repudiandae illo? Quo ratione quisquam officiis esse earum, aliquid animi temporibus! Ipsam consequuntur et consequatur eum pariatur a excepturi iusto explicabo aspernatur! Enim distinctio aspernatur sunt voluptate fuga libero dolores quas officia voluptas deserunt blanditiis dolore sed magni, dolorem hic dolor similique beatae. Eos iure sequi deserunt voluptatum sunt explicabo sit temporibus corrupti nostrum voluptate, hic consequuntur soluta commodi eum ducimus. Eveniet ea earum deleniti facere, explicabo ipsum illum, consectetur nobis quidem reiciendis magnam quam beatae, quisquam nihil vitae omnis?